name: Publish Packages

run-name: Publish package ${{ github.event.inputs.package  }} by @${{ github.actor }}

permissions:
  contents: write # allow committing/tags if you need it
  packages: write # allow pushing packages using GITHUB_TOKEN

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package path (relative to repo root)"
        required: true
        type: choice
        options:
          - dotnet/Common.Observability
          - npm/common-observability
      bump:
        description: "Version bump (patch/minor/major) or leave empty to skip auto"
        required: false
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  decide:
    runs-on: ubuntu-latest
    outputs:
      type: ${{ steps.detect.outputs.type }}
    steps:
      - uses: actions/checkout@v4
      - id: detect
        run: |
          pkg="${{ github.event.inputs.package }}"
          # Grab the first path segment (before the first /)
          top="${pkg%%/*}"

          if [ "$top" = "dotnet" ]; then
            echo "type=dotnet" >> "$GITHUB_OUTPUT"
          elif [ "$top" = "nest" ] || [ "$top" = "npm" ] || [ "$top" = "node" ]; then
            echo "type=npm" >> "$GITHUB_OUTPUT"
          else
            echo "type=unknown" >> "$GITHUB_OUTPUT"
            exit 1
          fi

  call-dotnet:
    if: needs.decide.outputs.type == 'dotnet'
    needs: decide
    uses: ./.github/workflows/publish-dotnet.yml
    with:
      package: ${{ github.event.inputs.package }}
      bump: ${{ github.event.inputs.bump }}
