name: Publish Packages
run-name: Publish ${{ github.event.inputs.package }} by @${{ github.actor }}

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package path (relative to repo root)"
        required: true
        type: choice
        options:
          - dotnet/Common.Observability
          - npm/common-observability
      bump:
        description: "Version bump type (patch/minor/major)"
        required: false
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  decide:
    runs-on: ubuntu-latest
    outputs:
      type: ${{ steps.detect.outputs.type }}
    steps:
      - id: detect
        run: |
          pkg="${{ github.event.inputs.package }}"
          top="${pkg%%/*}"
          if [ "$top" = "dotnet" ]; then
            echo "type=dotnet" >> "$GITHUB_OUTPUT"
          elif [ "$top" = "npm" ]; then
            echo "type=npm" >> "$GITHUB_OUTPUT"
          else
            echo "type=unknown" >> "$GITHUB_OUTPUT"; exit 1

  call-dotnet:
    if: needs.decide.outputs.type == 'dotnet'
    needs: decide
    uses: ./.github/workflows/publish-dotnet.yml
    with:
      package: ${{ github.event.inputs.package }}
      bump: ${{ github.event.inputs.bump }}
