name: Publish Package
run-name: Publish package by @${{ github.actor }}
permissions:
  contents: write # allow committing/tags if you need it
  packages: write # allow pushing packages using GITHUB_TOKEN

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package path (relative to repo root)"
        required: true
        type: choice
        options:
          - dotnet/Common.Observability
          - dotnet/Messing.Nuget
          - nest/observability-npm
          - nest/messing-npm
      version:
        description: "Version to publish (e.g. 1.2.3)"
        required: true
        type: string

jobs:
  decide:
    runs-on: ubuntu-latest
    outputs:
      type: ${{ steps.detect.outputs.type }}
    steps:
      - uses: actions/checkout@v4
      - id: detect
        run: |
          if [ -f "${{ github.event.inputs.package }}/package.json" ]; then
            echo "type=npm" >> "$GITHUB_OUTPUT"
          elif ls "${{ github.event.inputs.package }}"/*.csproj >/dev/null 2>&1; then
            echo "type=dotnet" >> "$GITHUB_OUTPUT"
          else
            echo "type=unknown" >> "$GITHUB_OUTPUT"
            exit 1
          fi

  call-dotnet:
    if: needs.decide.outputs.type == 'dotnet'
    needs: decide
    uses: ./.github/workflows/publish-dotnet.yml
    with:
      package: ${{ github.event.inputs.package }}
      version: ${{ github.event.inputs.version }}

  call-npm:
    if: needs.decide.outputs.type == 'npm'
    needs: decide
    uses: ./.github/workflows/publish-npm.yml
    with:
      package: ${{ github.event.inputs.package }}
      version: ${{ github.event.inputs.version }}
